steps:
  - id: "Docker build image"
    name: docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ms-auth:$SHORT_SHA', '-f', 'Dockerfile.prod', '.']

  - id: "Pushing Image"
    name: docker
    args: ['push','gcr.io/$PROJECT_ID/ms-auth:$SHORT_SHA']

  - id: "Migrations"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        sh entrypoint.prod.sh;

  - id: "Adjusting deployment file - k8s"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/ms-auth:$SHORT_SHA#g' k8s/app/deployment.yaml > k8s/app/deployment-new.yaml;
        cat k8s/app/deployment-new.yaml;

  - id: "Deploying k8s"
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/app/deployment-new.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-golang'

images: ['gcr.io/$PROJECT_ID/ms-auth']
