version: "3"

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile.prod
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./:/app
        networks:
            - server_network

networks:
    server_network:
        driver: bridge
